version: "3"
services:
  reverse_proxy:
    restart: always
    container_name: reverse_proxy
    build:
      context: .
      dockerfile: dockerfiles/traefik.Dockerfile
    command:
      - --providers.docker=true 
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_backend
      - --entrypoints.web-secured.address=:443 
      - --certificatesresolvers.myresolver.acme.email=ash.wilson@valimail.com
      - --certificatesresolvers.myresolver.acme.storage=/etc/traefik/tls/acme.json
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --accesslog=true
      - --log.level=debug
      - --entrypoints.web-secured.http.middlewares=client-cert-pass@docker
      - --providers.file.directory=/etc/traefik/
    ports:
      - "443:443"
    environment: 
      - XDG_CONFIG_HOME=/var/traefik_conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_tls:/etc/traefik/tls/
    networks:
      - "traefik_backend"

  flask:
    restart: always
    container_name: flask
    build:
      context: .
      dockerfile: ./dockerfiles/flask.Dockerfile
    environment:
      - ALLOW_DOMAINS=${ALLOW_DOMAINS}
      - ALLOW_HOSTS=${ALLOW_HOSTS}
      - BASE_DNS_NAME=${BASE_DNS_NAME}
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.client-cert-pass.passtlsclientcert.pem=true"
      - "traefik.http.routers.viewpage.rule=Host(`portal.${BASE_DNS_NAME}`)"
      - "traefik.http.routers.viewpage.entrypoints=web-secured"
      - "traefik.http.routers.viewpage.tls=true"
      - "traefik.http.routers.viewpage.tls.domains[0].main=portal.${BASE_DNS_NAME}"
      - "traefik.http.routers.viewpage.tls.certresolver=myresolver"
      - "traefik.http.routers.postapi.rule=Host(`api.${BASE_DNS_NAME}`)"
      - "traefik.http.routers.postapi.entrypoints=web-secured"
      - "traefik.http.routers.postapi.tls=true"
      - "traefik.http.routers.postapi.tls.options=clientcert@file"
      - "traefik.http.routers.postapi.tls.domains[0].main=api.${BASE_DNS_NAME}"
      - "traefik.http.routers.postapi.tls.certresolver=myresolver"
      
    networks:
      - "traefik_backend"
    volumes:
      - messages:/messaging/
    
networks:
  traefik_backend:

volumes:
  traefik_tls:
  messages:
